### ISSUE TITLE
Issue with modal dialogs

### ISSUE THREAD

**Issue by meybonomme** [amivaleo/Show-Desktop-Button#40] opened 2023-10-18 15:59 UTC
I want to thank You for this little but very useful extension!

Mostly it works very well, but I found one pretty annoying issue. When I have regular windows opened, click to the show desktop button hides all windows. Another click shows all open windows again, all is fine.

When I have opened window and pop-up window top of it (example: Extensions app window and Show Desktop Button settings pop-up window) first click in show desktop button hides all windows as normal. But another click doesn't show any windows anymore. It just does nothing. When i click Extensions app button in dash, these windows will be visible again, but pop-up window in most cases now is **behind** of main window. When I close pop-up window, Show Desktop Button acts normally again.

Is there something we can do with this issue?

**Comment by amivaleo** [comment] 2023-10-19 06:52
Hi!

I believe this is due to modal dialogs. I prepared a fix for this that seems to fix it but I need your help.

-> What's that "Extensions app window"? Do you mean this app https://github.com/mjakeman/extension-manager ?

-> Please try this and tell me what happens: only nautilus window open -> open nautilus settings from the menu -> click the panel indicator for the show-desktop-button extension.

**Comment by meybonomme** [comment] 2023-10-19 14:07
> -> What's that "Extensions app window"? Do you mean this app https://github.com/mjakeman/extension-manager ?
> 
I mean Gnome Extensions: https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/HEAD/subprojects/extensions-app


> -> Please try this and tell me what happens: only nautilus window open -> open nautilus settings from the menu -> click the panel indicator for the show-desktop-button extension.
> 
I have exactly the same behaviour: first click to the show desktop button hides Nautilus window with settings pop-up window, but another click does nothing. Click to the Nautilus icon in dash brings Nautilus window visible again, but pop-up window is behind of main window and I can't even close pop-up window or Nautilus window normally (can't close Nautilus before settings pop-up window is closed).

I will gladly help to make this extension better :)

**Comment by meybonomme** [comment] 2023-10-19 15:12
Yes, I want to test it and seems like main problem is now fixed, thank You! I will test it day or two and I will let You know about results. When all seems fine, You can release this fix for everyone.

One issue is still persist - if pop-up window is opened top of main window before show desktop button hides windows, then after window restore pop-up window is behind of main window. I tried and actually same happens if I will minimize and restore window with pop-up window from dash (I'm using dash to dock). Probably there is nothing You can do with this issue, because looks like it's not related with Your extension, it's more like Gnome shell or Dash to Dock extension issue.

**Comment by amivaleo** [comment] 2023-10-19 15:31
Indeed, I can't reproduce that second issue you say. Does it affect every app or just one?
I tested the fix I commited with both nautilus and that extension manager that you linked and now the extension works fine ("almost"). And I couldn't reproduce that "popup window no more on top". 🤔

I wrote that "almost" in parentheses because modal dialog (like the extension settings or app preferences) shouldn't be minimized. If they are sticked to the main window, they behave like the main window. If they are not, like in the case for extension settings, they won't be minimized by this extension.

It's not how I would like the extension to work, but forcing popup windows (whose better name is "modal dialogs") to minimize would lead to the bug that brought you here. :)

**Comment by meybonomme** [comment] 2023-10-19 15:45
Yes, it happens with every app. I will test it, maybe another extension causing this issue.

When I click show desktop button, I want hide ALL windows, including modal dialogs (thanks for the right term), I want to see clear desktop without any windows or dialogs. I like that show desktop button acts like it acts now, it hides all windows including modal dialogs. Like I said Dash to Dock acts in the same way, if I hide window from app button in dock, it hides also modal dialogs.

**Comment by amivaleo** [comment] 2023-10-19 16:07
Uhm... Try this extension alone, while all the others are disabled. 🤔

Anyway, now this extension should not hide all the modal dialogs. Only those that are sticked to another window.

I guess I have to dig a bit into dash2dock extension so to better understand how it hides all windows.

**Comment by meybonomme** [comment] 2023-10-20 20:34
I made some research and modal dialog issue IS NOT related with Show Desktop Button extension.
I have this issue with only enabled extension is Show Desktop Button and also with only Dash to Dock extension enabled.

When I try to record screencast with GNOME inbuilt org.gnome.Shell.Screencast then issue will be gone until I close Screencast and it's not possible even record this issue.

I'm pretty sure that is GNOME Shell or Wayland issue. I'm using Gnome 45.0 and Wayland session on Fedora 39.
Are You using Gnome 45 with Wayland or with X11? If your windowing system is not Wayland, that's why You don't have this issue.

After the fix You made, Show Desktop Button works perfectly even with open modal dialogs on my side. Thank You :+1:

**Comment by amivaleo** [comment] 2023-10-22 07:49
Wait.

You're telling me that the screencast app didn't work properly if this extension is triggered while recording the screen?

That's a much bigger bug you got here. 😱

But you said that after the latest fix, now it works properly, right? If so, it could be because the screencast layout is defined as a "modal dialog".

There might be a mismatch between what users and devs call a thing. I mean that, maybe, a "modal dialog" for a dev is some special window with some special property and, one of these, is to be not-minimizable. So the fix I applied also fixes other, unexpected, BIG bugs. 😱

I think I'm delivering the fix to EGO now.

**Comment by amivaleo** [comment] 2023-10-22 08:02
Delivered.

I close here since I believe I fixed the issue. Thank you! :)

**Closed by amivaleo** 2023-10-22 08:02 UTC
Labels: bug

**Comment by meybonomme** [comment] 2023-10-22 17:07
> Wait.
> 
> You're telling me that the screencast app didn't work properly if this extension is triggered while recording the screen?
> 
> That's a much bigger bug you got here. 😱

Screencast app works very fine and without issues with this extension :wink: 
This annoying modal dialogs behind main window bug is gone every time when Screencast is active :smiley: 
So I can't record bug, because bug is gone at this moment.

I'm sure this bug is also Gnome Shell related, because Your extension and Dash To Dock both acting the same way.

> But you said that after the latest fix, now it works properly, right? If so, it could be because the screencast layout is defined as a "modal dialog".
> 
The modal dialog behind mind mine window after windows minimized bug is still there, but You can't probably do anything with that.

> I think I'm delivering the fix to EGO now.
Of course, this update is worth of that :+1:

**Comment by amivaleo** [comment] 2023-10-23 06:09
> The modal dialog behind mind mine window after windows minimized bug is still there, but You can't probably do anything with that.

The fact is that I can't reproduce that. 🤔

Are you using X11? It could be because of that.

**Comment by meybonomme** [comment] 2023-10-23 16:27
>I'm pretty sure that is GNOME Shell or Wayland issue. I'm using Gnome 45.0 and Wayland session on Fedora 39.
Are You using Gnome 45 with Wayland or with X11? If your windowing system is not Wayland, that's probably why You don't have this issue.

As I said I'm using Wayland. Probably this issue is related with Wayland and that's why You can reproduce this bug with X11. Wayland is pretty good already (even the fractional scaling really works now) but it's not bugless.

**Comment by meybonomme** [comment] 2023-10-24 21:13
>Please, tell me exactly which app gives this bug. I need to reproduce it in order to have some hope to fix it. :(

With every app wich have modal dialog open. This issue is not app related, every modal window causing this when minimized. I don't believe You can fix this issue. We both have Gnome 45 and Wayland, but maybe different distro base is keyword?

**Comment by amivaleo** [comment] 2023-10-25 06:51
> With every app wich have modal dialog open.

I can't reproduce it. 🤔

[Video del 2023-10-25 08-49-26.webm](https://github.com/amivaleo/Show-Desktop-Button/assets/24316547/8ecca770-260a-4e33-afc5-ea88fd622120)

> We both have Gnome 45 and Wayland, but maybe different distro base is keyword?

Fedora 38 user here. 🙋‍♂️

But it shouldn't matter...

Have you tried with only this extension enabled?

**Comment by meybonomme** [comment] 2023-10-25 11:13
As I said, I can't also reproduce this issue when screencast is active and recording. Then all works as excepted.

If You also using Fedora and Wayland, then I have only one though - this bug is specially Fedora 39 (beta) related. I think we have to wait until Fedora 39 is released and You got the upgrade. Exact release date is unclear, because they have some final blocker bugs: https://qa.fedoraproject.org/blockerbugs/milestone/39/final/buglist and they will release when these blocker bugs are removed and Fedora 39 is ready.

**Comment by amivaleo** [comment] 2023-10-26 05:49
> As I said, I can't also reproduce this issue when screencast is active and recording.

I can't in any condition.

I'll wait to have Fedora 39 installed on my pc, that I won't do till it's released. 👍️

**Comment by amivaleo** [comment] 2023-11-13 18:32
I updated to Fedora 39 and yet I can't reproduce the issue here.

Do you have news?
