### ISSUE TITLE
Conflict between hide all regular windows keyboard shortcut and Show Desktop button

### ISSUE THREAD

**Issue by meybonomme** [amivaleo/Show-Desktop-Button#43] opened 2023-10-20 21:57 UTC
I found another issue. If I hide all windows with GNOME keyboard shortcut, I can't unhide them with Show Desktop Button and vice versa.

Is there anything You can do with this issue?

**Comment by amivaleo** [comment] 2023-10-21 12:06
This might be a true showstopper.

I'm prone to think that the native functionality works in a pretty different way. Meaning: it does not actually minimize the open windows, it might do something different.

I believe this because this extension simply checks for open windows. If any, it minimize them. If all windows are minimized, it uniminized them all again.

The statuses "minimized" and "unminimized" are not added by this extension. They are native properties of every application window.

If the native hide/show toggle triggered by a shortcut conflicts with this extension, my conclusion is that it does something other than minimizing/unminimizing.

Can you do me a favour? Can you please check how that shorcut works with the dash-to-dock button that triggers the very same action?

If the behaviour is different, and it works as expected, I really need to dig into that extension's code...

**Comment by meybonomme** [comment] 2023-10-21 20:41
> I'm prone to think that the native functionality works in a pretty different way. Meaning: it does not actually minimize the open windows, it might do something different.
> 
Native hide is without any animations. I think it's just changing desktop layers priority. When windows are hidden, desktop background layer will be top of windows layers.

> Can you do me a favour? Can you please check how that shorcut works with the dash-to-dock button that triggers the very same action?
> 
Show Desktop Button and Dash To Dock acting exactly the same way. But native hide function is different. Because window minimizing is not native GNOME function. That's why they hiding windows, not minimizing them.

We need another extension to "overwrite" GNOME native hiding function with minimizing function. Do You have also some ideas?

Dash To Dock is great extension, but it need some more active maintainer, who have time and interest to tweak out bugs and add more functionality.  Dash To Panel have more functionality, but GUI is very outdated and I don't want Windows feeling, when I'm using Linux. Fedora with GNOME feeling is much better and feels like fresh air :wink:

**Comment by meybonomme** [comment] 2023-10-21 20:52
Please do this test:

1. Put one ore more visible windows to desktop
2. Press your "Hide all regular windows" keyboard shortcut
3. Now click to the Show Desktop button
4. Press "Hide all regular windows" keyboard shortcut again

Native functionality can't unhide windows, because they won't in desktop anymore. Native function just changing layers, I'm pretty sure.

**Comment by amivaleo** [comment] 2023-10-22 07:14
> Native hide [...] 's just changing desktop layers priority.

> We need [...] to "overwrite" GNOME native hiding function [...]. Do You have also some ideas?

I remember someone told me that windows have no property like "z-index" in gnome. I've still to fully understand that. Anyway, it might be that desktop and "all" windows stay at least in separate layers and the native functionality switch them as you say.

If that's the case, I have no clue how to tackle this. And this is an answer also to your question...




> Please do this test [...]

I already did that. I'm fully aware that the two functions work in a different way. :(

> GNOME Shell just holds another layer [...] and Show Desktop Button changes windows state somewhere in the unvisible background.

And that's exactly why I feel I can't fix the extension. I also checked dash-to-panel to understand how it behaves, and yes, as you say, it dows exactly what this extension does.

If I ever happen to find how to trigger the very native functionality, I will surely try to make this extension use it. 


> Dash To Dock is great extension [...]. Dash To Panel have more functionality [...]. Fedora with GNOME feeling is much better and feels like fresh air 😉

I use almost vanilla gnome. Having a 16:9 screen ratio, I prefer the vertical view it used to have a few versions ago. This is the deepest change to the UI that I use.

**Comment by amivaleo** [comment] 2023-10-22 07:50
Fixed in version 34

**Closed by amivaleo** 2023-10-22 07:50 UTC
Labels: bug, help wanted

**Comment by meybonomme** [comment] 2023-10-22 17:40
>...I prefer the vertical view it used to have a few versions ago. This is the deepest change to the UI that I use.

How You did that? I'm also interested about vertical view in appdrawer but without changing native look.

**Comment by amivaleo** [comment] 2023-10-23 06:18
> How You did that?

Here! https://extensions.gnome.org/extension/5177/vertical-workspaces/

> One solution would be add keyboard shortcut support to Show Desktop Button extension.

Yeah... I really need some spare time to think about this and a lot more to learn how to implement it. 😅

**Comment by meybonomme** [comment] 2023-10-23 16:37
>Here! https://extensions.gnome.org/extension/5177/vertical-workspaces/

Thank You! I know this extension, but it changing app drawer's look and behaviour too much for me. Rather sticking to the native solution. I hoped there is any other and better solution :wink

**Comment by amivaleo** [comment] 2023-10-24 12:37
>  this extension [changes] look and behaviour too much for me

It allows for a lot of customization. o.O

I set it so to faithfully reproduce the gnome UI before it switched to horizontal fashion.
