### ISSUE TITLE
Outdated for Fedora 40

### ISSUE THREAD

**Issue by cbelleza** [amivaleo/Show-Desktop-Button#47] opened 2024-04-24 18:09 UTC
I installed Fedora 40, and the extensions says is outdated... possible not compatible with Gnome 46

**Comment by amivaleo** [comment] 2024-04-24 18:14
Hi there! :)

I'm updating my Fedora right now. I am confindent I'll put an update for this extension on EGO (the extension website) in a few hours. Then, it's just a matter of getting it approved by a reviewer. ;)

Duplicate of #46.

**Closed by amivaleo** 2024-04-24 18:14 UTC
